# Generated by Django 4.2.10 on 2025-04-19 16:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='EbayListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField()),
                ('item_id', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('seller', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebay_listings', to='product_matcher.productimage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
