# Generated by Django 4.2.10 on 2025-04-19 21:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import product_matcher.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_matcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', validators=[product_matcher.models.validate_file_size]),
        ),
        migrations.CreateModel(
            name='VisionAPICall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('api_response', models.JSONField()),
                ('labels', models.JSONField(blank=True, null=True)),
                ('text', models.JSONField(blank=True, null=True)),
                ('detected_objects', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(null=True)),
                ('product_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_api_calls', to='product_matcher.productimage')),
            ],
            options={
                'ordering': ['-request_timestamp'],
            },
        ),
    ]
